# Generated by Django 4.2.6 on 2023-10-12 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qr_code', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='qr_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_set', to='qr_code.qrcode', verbose_name='QR Code'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
