# Generated by Django 4.2.6 on 2023-10-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_code', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='title',
            field=models.CharField(default='Title', max_length=255, verbose_name='Title'),
        ),
    ]
